services:
  mf-shell:
    build:
      context: .
      dockerfile: apps/mf-shell/Dockerfile
      args:
        VERDACCIO_URL: http://192.168.42.44:10100
    restart: unless-stopped
    ports:
      - "10500:80"
      - "20500:443"
    environment:
      PORT: "80"
      SSL_PORT: "443"
      USE_SSL: "true"
      CERT_PATH: /proyectos/certs
      NGINX_TYPE: spa
    volumes:
      - /proyectos/certs:/proyectos/certs:ro

  mf-auth:
    build:
      context: .
      dockerfile: apps/mf-auth/Dockerfile
      args:
        VERDACCIO_URL: http://192.168.42.44:10100
    restart: unless-stopped
    ports:
      - "10501:80"
      - "20501:443"
    environment:
      PORT: "80"
      SSL_PORT: "443"
      USE_SSL: "true"
      CERT_PATH: /proyectos/certs
      NGINX_TYPE: remote
    volumes:
      - /proyectos/certs:/proyectos/certs:ro

  mf-home:
    build:
      context: .
      dockerfile: apps/mf-home/Dockerfile
      args:
        VERDACCIO_URL: http://192.168.42.44:10100
    restart: unless-stopped
    ports:
      - "10502:80"
      - "20502:443"
    environment:
      PORT: "80"
      SSL_PORT: "443"
      USE_SSL: "true"
      CERT_PATH: /proyectos/certs
      NGINX_TYPE: remote
    volumes:
      - /proyectos/certs:/proyectos/certs:ro

  mf-emergency:
    build:
      context: .
      dockerfile: apps/mf-emergency/Dockerfile
      args:
        VERDACCIO_URL: http://192.168.42.44:10100
    restart: unless-stopped
    ports:
      - "10503:80"
      - "20503:443"
    environment:
      PORT: "80"
      SSL_PORT: "443"
      USE_SSL: "true"
      CERT_PATH: /proyectos/certs
      NGINX_TYPE: remote
    volumes:
      - /proyectos/certs:/proyectos/certs:ro

  mf-hospital:
    build:
      context: .
      dockerfile: apps/mf-hospital/Dockerfile
      args:
        VERDACCIO_URL: http://192.168.42.44:10100
    restart: unless-stopped
    ports:
      - "10504:80"
      - "20504:443"
    environment:
      PORT: "80"
      SSL_PORT: "443"
      USE_SSL: "true"
      CERT_PATH: /proyectos/certs
      NGINX_TYPE: remote
    volumes:
      - /proyectos/certs:/proyectos/certs:ro

  mf-ambulatorio:
    build:
      context: .
      dockerfile: apps/mf-ambulatorio/Dockerfile
      args:
        VERDACCIO_URL: http://192.168.42.44:10100
    restart: unless-stopped
    ports:
      - "10505:80"
      - "20505:443"
    environment:
      PORT: "80"
      SSL_PORT: "443"
      USE_SSL: "true"
      CERT_PATH: /proyectos/certs
      NGINX_TYPE: remote
    volumes:
      - /proyectos/certs:/proyectos/certs:ro

  mf-auditoria:
    build:
      context: .
      dockerfile: apps/mf-auditoria/Dockerfile
      args:
        VERDACCIO_URL: http://192.168.42.44:10100
    restart: unless-stopped
    ports:
      - "10506:80"
      - "20506:443"
    environment:
      PORT: "80"
      SSL_PORT: "443"
      USE_SSL: "true"
      CERT_PATH: /proyectos/certs
      NGINX_TYPE: remote
    volumes:
      - /proyectos/certs:/proyectos/certs:ro
