services:
  mf-shell:
    build:
      context: .
      dockerfile: apps/mf-shell/Dockerfile
      args:
        VERDACCIO_URL: http://host.docker.internal:10100
      extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "10500:80"

  mf-auth:
    build:
      context: .
      dockerfile: apps/mf-auth/Dockerfile
      args:
        VERDACCIO_URL: http://host.docker.internal:10100
      extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "10501:80"

  mf-home:
    build:
      context: .
      dockerfile: apps/mf-home/Dockerfile
      args:
        VERDACCIO_URL: http://host.docker.internal:10100
      extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "10502:80"

  mf-emergency:
    build:
      context: .
      dockerfile: apps/mf-emergency/Dockerfile
      args:
        VERDACCIO_URL: http://host.docker.internal:10100
      extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "10503:80"

  mf-hospital:
    build:
      context: .
      dockerfile: apps/mf-hospital/Dockerfile
      args:
        VERDACCIO_URL: http://host.docker.internal:10100
      extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "10504:80"

  mf-ambulatorio:
    build:
      context: .
      dockerfile: apps/mf-ambulatorio/Dockerfile
      args:
        VERDACCIO_URL: http://host.docker.internal:10100
      extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "10505:80"

  mf-auditoria:
    build:
      context: .
      dockerfile: apps/mf-auditoria/Dockerfile
      args:
        VERDACCIO_URL: http://host.docker.internal:10100
      extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "10506:80"
